import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from '@/contexts/AppContext';
import { productsService } from '@/utils/supabase/products';
import { categoriesService } from '@/utils/supabase/categories';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [products, categories] = await Promise.all([
    productsService.getProducts(),
    categoriesService.getCategories()
  ]);

  console.log('Products:', products);
  console.log('Categories:', categories);

  return (
    <html lang="en" className="bg-[#EBEEF6]">
      <body className={`${inter.className} bg-[#EBEEF6] flex flex-col min-h-screen items-center`}>
        <AppProvider initialProducts={products} initialCategories={categories}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}